# Generated by Django 3.2.16 on 2022-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0006_auto_20221024_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
